homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

ios:
# Text to speech
tts:
  platform: google

influxdb:
  include:
    entities:
       - automation.motion_detection
       - automation.close_door
       - automation.open_door
       - sensor.fibaro_system_fgms001_motion_sensor_luminance
       - sensor.fibaro_system_fgms001_motion_sensor_temperature
       - sensor.fibaro_system_fgs213_switch_energy
       - sensor.widom_ume304_energy_driven_switch_power_2
       - sensor.widom_ume304_energy_driven_switch_voltage
       - sensor.widom_ume304_energy_driven_switch_current

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
device_tracker: !include device_tracker.yaml
script: !include_dir_merge_named scripts
shell_command: !include_dir_merge_named shell_commands
input_boolean: !include_dir_merge_named input_boolean

zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true
  network_key: !secret network_key
mqtt:

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 50
  icon: mdi:city

zone 3:
  name: Cianta
  latitude: !secret cianta_latitude
  longitude: !secret cianta_longitude
  radius: 150
  icon: mdi:barley

zone 4:
  name: Reset
  latitude: !secret reset_latitude
  longitude: !secret reset_longitude
  radius: 50
  icon: mdi:city

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids: !secret telegram_allowed_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

hdmi_cec:
  devices:
    0: TV
    2: PS4

switch:
  - platform: command_line
    switches:
      tv:
        command_on: "echo on 0 | cec-client -s -d 1"
        command_off: "echo standby 0 | cec-client -s -d 1"
